"""Store product snapshot in order table

Revision ID: 91a8a7fe1433
Revises: fa1ad2a7c2e9
Create Date: 2026-02-04 15:51:54.230271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a8a7fe1433'
down_revision = 'fa1ad2a7c2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('product_image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('product_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('product_gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('seller_id')
        batch_op.drop_column('product_gender')
        batch_op.drop_column('product_category')
        batch_op.drop_column('product_image')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
