"""add status for block

Revision ID: e7557bfbd50b
Revises: d8e69753b045
Create Date: 2026-01-19 18:20:01.721479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7557bfbd50b'
down_revision = 'd8e69753b045'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Add column as nullable
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('status', sa.String(length=10), nullable=True)
        )

    # 2. Fill existing rows
    op.execute("UPDATE user SET status = 'active'")

    # 3. Make column NOT NULL
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column(
            'status',
            nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
